path: /home/sarfraz/coding/BPP-Boilerplate-SDK/packages/bpp-sdk/src/specifications/1.1.0/api/transaction/build/transaction.yaml
version: 1.1.0
db:
  mongo:
    mongo_uri: mongodb://localhost:27017
tables:     
  - name: "Descriptor"
    for: Descriptor
    admin_ui: true
    schema: 
      title: 
        type: string
        as: name
      description:
        type: string
        as: short_desc
      code: 
        type: string
        as: code
      images: 
        type: object[]
        as: images
        children:
          icon:
            type: upload
            as: url
  - name: "User_Catalog"
    for: Catalog
    admin_ui: true
    schema: 
      descriptor:
        type: ref
        as: descriptor
        $ref: Descriptor
        $ref_key: name
  - name: Provider
    for: Provider
    admin_ui: true
    schema:
      name:
        type: string
        as: descriptor.name
      code:
        type: string
        as: descriptor.code
      images:
        type: object[]
        as: descriptor.images
        children:
          icon:
            type: upload
            as: url
      category:
        type: enum
        as: category_id
        enum:
        - code: "MINI"
          name: "MINI"
        - code: "AUTO"
          name: "AUTO"
        - code: "MICRO"
          name: "MICRO"
        - code: "SEDAN"
          name: "SEDAN"
      items:
        type: object[]
        as: items
        children:
          id:
            type: string
            as: id
          price:
            type: object
            as: price
            children:
              value:
                type: string
                as: value
      # title:
      #   type: string
      #   as: descriptor.name
      # description:
      #   type: string
      #   as: descriptor.short_desc
      # category:
      #   type: enum
      #   enum: 
      #     - code: "1"
      #       name: "Category 1"
      #     - code: "2"
      #       name: "Category 2"
      #     - code: "3"
      #       name: "Category 3"
      #   as: descriptor.code
      # images:
      #   type: object[]
      #   as: descriptor.images
      #   children:
      #     icon:
      #         type: upload
      #         as: url

gateway:
    uri: https://gateway.becknprotocol.io/bg
    registry_uri: https://registry.becknprotocol.io/subscribers
app:
    id: sarfraz-bpp-dsep
    unique_id: sarfraz-bpp-dsep-key
    uri: https://sarfraz-bpp.loca.lt
    ttl: PT10M
    city: std:080
    country: IND
    public_key: YcnZ8xyT2M2onkgI+t6W9Ct+6FnsBuiSCa8WqPDLy8k=
    private_key: SiVZmCtmzKdhZ3VUG5ONYKLDdtF1slRPEGZWHMS3DhthydnzHJPYzaieSAj63pb0K37oWewG6JIJrxao8MvLyQ==
